on:
  push:
    branches:
      - main

name: Test_Coverage

jobs:
  test_coverage:
    name: Test and Coverage
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "16.x"
      - name: Install node dependencies
        run: yarn
      - name: Build App
        run: yarn test

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
